---
name: "Container Structure Test Action"
description: "A composite action to verify a container structure using GoogleContainerTools/container-structure-test."
branding:
  icon: 'check'
  color: 'blue'
inputs:
  image:
    description: ""
    required: true
  config_file:
    description: ""
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        case "$RUNNER_OS" in
          Linux)
            curl --location \
              --output container-structure-test \
              https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64
            ;;

          macOS)
            curl --location \
              --output container-structure-test \
              https://storage.googleapis.com/container-structure-test/latest/container-structure-test-darwin-amd64
            ;;

          *)
            echo "$RUNNER_OS is not supported! Use a linux or macOs one instead."
            exit 1
            ;;
        esac

        chmod +x container-structure-test
        container-structure-test test --image "${{ inputs.image }}" --config "${{ inputs.config_file }}"
      shell: bash
