---
name: "Container Structure Test Action"
description: "A composite action to verify a container structure using GoogleContainerTools/container-structure-test."
branding:
  icon: 'check'
  color: 'blue'
inputs:
  version:
    description: |
      The version of container-structure-test to be installed.
      Default to 'latest' if not provided.
      See the key property in https://storage.googleapis.com/container-structure-test for available versions.
    required: false
    default: "latest"
  image:
    description: |
      The full docker image tag to be verified.
    required: true
  config_file:
    description: |
      The path to the container structure configuration file.
    required: true
  install_path:
    description: |
      The path to where the executable will be installed to.
    required: false
    default: ".bin"
runs:
  using: "composite"
  steps:
    - uses: actions/cache@v3
      with:
        path: ${{ inputs.install_path }}
        key: ${{ runner.os }}-container-structure-test
        restore-keys: |
          ${{ runner.os }}-container-structure-test

    - run: |
        if [[ -x ${{ inputs.install_path }}/container-structure-test ]]; then
          echo "container-structure-test found in cache. It will not be installed for this run."
        else
          case "$RUNNER_OS" in
            Linux)
              curl --location \
                --output container-structure-test \
                "https://storage.googleapis.com/container-structure-test/${{ inputs.version }}/container-structure-test-linux-amd64"
              ;;

            macOS)
              curl --location \
                --output container-structure-test \
                "https://storage.googleapis.com/container-structure-test/${{ inputs.version }}/container-structure-test-darwin-amd64"
              ;;

            *)
              echo "$RUNNER_OS is not supported! Use a linux or macOs one instead."
              exit 1
              ;;
          esac

          mkdir -vp "./${{ inputs.install_path }}"
          echo "./${{ inputs.install_path }}" >> "$GITHUB_PATH"

          chmod +x container-structure-test
          mv -v container-structure-test "./${{ inputs.install_path }}/container-structure-test"
        fi

      shell: bash

    - run: |
        container-structure-test test --image "${{ inputs.image }}" --config "${{ inputs.config_file }}"
      shell: bash
